version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pokertracker_postgres
    environment:
      POSTGRES_USER: cxz2286
      POSTGRES_PASSWORD: cuixianze123
      POSTGRES_DB: pokertracker
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    image: cxz22865527/poker-traker:latest
    container_name: pokertracker_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pokertracker
      SPRING_DATASOURCE_USERNAME: cxz2286
      SPRING_DATASOURCE_PASSWORD: cuixianze123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
